/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_util_Utils */

#ifndef _Included_com_util_Utils
#define _Included_com_util_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_util_Utils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_util_Utils_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_util_Utils
 * Method:    unimplementedStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_util_Utils_unimplementedStringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_util_Utils
 * Method:    calc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_util_Utils_calc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_util_Utils
 * Method:    writeContentToFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_util_Utils_writeContentToFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
